#!/bin/sh
MYSELF=`which "$0" 2>/dev/null`
[ $? -gt 0 -a -f "$0" ] && MYSELF="./$0"
java=java
if test -n "$JAVA_HOME"; then
    java="$JAVA_HOME/bin/java"
fi

EXECUTE_FLAG=1
for param in $@; do
  test "$param" = "-d" && EXECUTE_FLAG=0
  test "$param" = "--dryrun" && EXECUTE_FLAG=0
done

if (test $EXECUTE_FLAG -eq 0); then
  exec "$java" -jar $MYSELF "$@"
else
  exec "$java" -jar $MYSELF "$@" | xargs -0 -o bash -c
fi

exit $?
