#!/usr/bin/env bash

aws sts get-caller-identity > /dev/null 2>&1 || { echo "Default AWS Credentials are NOT valid"; exit 1; }

usage() {
  echo "Usage:"
  echo "  session <app> <stack> <stage>"
  exit 1
}

app=$1; shift
stack=$1; shift
stage=$1; shift

if [[ -z $stage || $1 ]]; then
   usage
fi

aws ec2 describe-instances \
    --filters \
        "Name=tag:App,Values=$app" \
        "Name=tag:Stack,Values=$stack" \
        "Name=tag:Stage,Values=$stage" \
        "Name=instance-state-name,Values=running" \
    --query "Reservations[].Instances[] | sort_by(@, &LaunchTime)[0] | InstanceId" \
  | xargs -o aws ssm start-session --target
