name: Snyk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@ts/update-snyk-workflow
    with:
      DEBUG: true
      ORG: guardian-security
      SKIP_NODE: true
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
